// Copyright (C) 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef ICING_MONKEY_TEST_ICING_MONKEY_TEST_RUNNER_H_
#define ICING_MONKEY_TEST_ICING_MONKEY_TEST_RUNNER_H_

#include <cstdint>
#include <memory>
#include <string>
#include <unordered_map>

#include "icing/file/filesystem.h"
#include "icing/icing-search-engine.h"
#include "icing/monkey_test/in-memory-icing-search-engine.h"
#include "icing/monkey_test/monkey-test-generators.h"
#include "icing/monkey_test/monkey-test-util.h"
#include "icing/proto/schema.pb.h"
#include "icing/util/clock.h"

namespace icing {
namespace lib {

class IcingMonkeyTestRunner {
 public:
  IcingMonkeyTestRunner(IcingMonkeyTestRunnerConfiguration config);
  IcingMonkeyTestRunner(const IcingMonkeyTestRunner&) = delete;
  IcingMonkeyTestRunner& operator=(const IcingMonkeyTestRunner&) = delete;

  SetSchemaResultProto SetSchema(SchemaProto&& schema);

  // This function must and should only be called before running the monkey
  // test.
  void Initialize();

  // Run the monkey test with num operations.
  void Run(uint32_t num);

  // APIs supported in icing search engine.
  void DoUpdateSchema();
  void DoGet();
  void DoGetAllNamespaces();
  void DoPut();
  void DoDelete();
  void DoDeleteByNamespace();
  void DoDeleteBySchemaType();
  void DoDeleteByQuery();
  void DoSearch();
  void DoJoinSearch();
  void DoGetDebugInfo();
  void DoGetNextPage();

  // Operations with no observable side-effects.
  void DoPersistToDisk();
  void ReloadFromDisk();
  void DoOptimize();
  void DoMaintainAnnIndex();

 private:
  void InternalSearch(bool is_join_search);

  void CreateIcingSearchEngine();
  // Reloads the in-memory icing from the disk.
  void ReloadInMemoryIcing();

  // A struct that represents an Icing token and information about the
  // corresponding query.
  struct QueryState {
    uint64_t next_page_token;
    int64_t query_timestamp_ms;
    int num_to_snippet;
    int num_matches_per_property;
    bool is_snippetable_query;
    bool is_projection_enabled;
  };

  // TODO(b/542593471):  Move this function to anonymous namespace function once
  // we fix pagination bug.
  void CheckResults(const SearchResultProto& actual_search_result,
                    const SearchResultProto& expected_search_result,
                    int64_t query_timestamp_ms, int& num_to_snippet,
                    int num_matches_per_property, bool& is_snippetable_query,
                    bool is_projection_enabled);

  void CheckResults(const SearchResultProto& actual_search_result,
                    const SearchResultProto& expected_search_result,
                    QueryState& query_state);

  std::unique_ptr<Clock> clock_;
  IcingMonkeyTestRunnerConfiguration config_;
  MonkeyTestRandomEngine random_;
  Filesystem filesystem_;
  std::string icing_dir_;
  std::unique_ptr<InMemoryIcingSearchEngine> in_memory_icing_;
  std::unique_ptr<IcingSearchEngine> icing_;

  std::unique_ptr<MonkeySchemaGenerator> schema_generator_;
  std::unique_ptr<MonkeyDocumentGenerator> document_generator_;

  // A map from in-memory icing token to QueryState.
  // We choose to map from in-memory icing token to the real Icing token because
  // Icing tokens are generated by adding a pointer address and the current time
  // (i.e. non-deterministic) whereas in-memory Icing tokens are generated by
  // random sampling from a distribution.
  std::unordered_map<uint64_t, QueryState>
      in_memory_token_to_icing_token_;

  // A map from schema type to the timestamp of the last index incompatible
  // update.
  // If the schema type is not in the map, then the schema type never had an
  // index incompatible update.
  // TODO(b/542593471):  Remove once the incorrect snippet due to pagination
  // state and icing internal id changes is fixed.
  std::unordered_map<std::string, int64_t>
      schema_to_last_index_incompatible_update_;
};

}  // namespace lib
}  // namespace icing

#endif  // ICING_MONKEY_TEST_ICING_MONKEY_TEST_RUNNER_H_
